version: '3.1'

services:

 discovry:
  container_name: discovery-service
  image: discovery-service
  ports:
   - "8761:8761"
  networks:
   - social-network

 db:
  image: 'postgres'
  container_name: db
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=password
  networks:
    - social-network

 auth-service:
   container_name: auth-service
   image: auth-service
   ports:
     - "8101:8101"
   networks:
     - social-network

 friend-service:
   container_name: friend-service
   image: friend-service
   ports:
     - "8078:8078"
   networks:
     - social-network

 gateway:
   container_name: gateway-service
   image: gateway-service
   ports:
     - "8222:8222"
   networks:
     - social-network

 interaction-service:
   container_name: interaction-service
   image: interaction-service
   ports:
     - "8070:8070"
   networks:
     - social-network


 post-service:
   container_name: post-service
   image: post-service
   ports:
     - "8074:8074"
   networks:
     - social-network

 zipkin:
  container_name: zipkin
  image: openzipkin/zipkin
  ports:
   - "9411:9411"
  networks:
   - zipkin

 zookeeper:
   image: confluentinc/cp-zookeeper:latest
   environment:
    ZOOKEEPER_CLIENT_PORT: 2181
    ZOOKEEPER_TICK_TIME: 2000
   ports:
    - 2181:2181

 kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
     - zookeeper
    ports:
     - 9092:9092
     - 29092:29092
    environment:
     KAFKA_BROKER_ID: 1
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  social-network:
    driver: bridge
  zipkin:
    driver: bridge